services:

  pg-bot-tap-quiz:
    # * rename as needed, put the right adress to the web service down below
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-BotTapQuiz} # * rename all here and put all right values to the web service down below
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # *
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # *
    ports:
      - "5432:5432"
    networks:
      - inner_bot
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_RUN_PORT:-8000}:8000"
    networks:
      - inner_bot
    depends_on:
      - pg-bot-tap-quiz
    environment:
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS:-pg-bot-tap-quiz} # * 
      - POSTGRES_DB=${POSTGRES_DB:-BotTapQuiz} # *
      - POSTGRES_USER=${POSTGRES_USER:-postgres} # *
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password} # *
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-10}
      - POSTGRES_MAX_OVERFLOW=${POSTGRES_MAX_OVERFLOW:-20}

      - DEBUG=${DEBUG:-True} # Can be True for now, not making bot unsecure, just loading the stdout stream, causing slowdowns
      - APP_RUN_PORT=${APP_RUN_PORT:-8000}
      - APP_RUN_WORKERS=${APP_RUN_WORKERS:-1}  # TODO: Make 4 at least for production (( ! ))

      - SQLADMIN_SECRET_KEY=${SQLADMIN_SECRET_KEY:-sqladmin_secret_key} # UNSECURE, update it
      - SQLADMIN_USERNAME=${SQLADMIN_USERNAME:-admin} # UNSECURE, update it
      - SQLADMIN_PASSWORD=${SQLADMIN_PASSWORD:-password} # UNSECURE, update it

      - BASE_SERVER_URL=${BASE_SERVER_URL:-https://dkjsyk-ip-184-22-35-246.tunnelmole.net}
      - BASE_BOT_URL=${BASE_BOT_URL:-https://jrqmts-ip-184-22-35-246.tunnelmole.net} # Better to put the inner (docker) network address (( ! )) For now unused but gonna be implemented

    command: /app/start.sh
    volumes:
      - media:/app/media
      - .:/app # DEBUG, DELETE ON DEPLOY (( ! ))

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    ports:
      - "${BOT_PORT:-8080}:8080" # TODO: Make configurable
    networks:
      - inner_bot
    depends_on:
      - pg-bot-tap-quiz
    environment:
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS:-pg-bot-tap-quiz} # * 
      - POSTGRES_DB=${POSTGRES_DB:-BotTapQuiz} # *
      - POSTGRES_USER=${POSTGRES_USER:-postgres} # *
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password} # *
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-10}
      - POSTGRES_MAX_OVERFLOW=${POSTGRES_MAX_OVERFLOW:-20}

      - DEBUG=${DEBUG:-True}
      - BOT_PORT=${BOT_PORT:-8080}

      - BASE_SERVER_URL=${BASE_SERVER_URL:-https://dkjsyk-ip-184-22-35-246.tunnelmole.net}
      - BASE_BOT_URL=${BASE_BOT_URL:-https://jrqmts-ip-184-22-35-246.tunnelmole.net}
      # (( ! ))
      # - BOT_TOKEN=${BOT_TOKEN:-7638664164:AA...}  # Fill with the bot token or make a .env file with BOT_TOKEN=...

    command: /bot/start-bot.sh
    volumes:
      - .:/bot # DEBUG, DELETE ON DEPLOY (( ! ))

networks:
  inner_bot:
    external: false
    driver: bridge

volumes:
  pg_data:
  media:
