services:

  pg-bot-tap-quiz:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-BotTapQuiz}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - inner_bot
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_RUN_PORT:-8000}:8000"
    networks:
      - inner_bot
    depends_on:
      - pg-bot-tap-quiz
    environment:
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS:-pg-bot-tap-quiz}
    command: /app/start.sh
    volumes: 
      - media:/app/media

networks:
  inner_bot:
    external: false
    driver: bridge

volumes:
  pg_data:
  media:
