services:

  pg-bot-tap-quiz:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-BotTapQuiz}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    # networks:
    #   - inner_bot
    volumes:
      - pg_data:/var/lib/postgresql/data

# networks:
#   inner_bot:
#     external: false
#     driver: bridge

volumes:
  pg_data:
