"""button is_inline param del

Revision ID: 6a105cba6d98
Revises: c8f6f4d1d98c
Create Date: 2024-11-09 16:55:04.613601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a105cba6d98'
down_revision: Union[str, None] = 'c8f6f4d1d98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'is_inline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('is_inline', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
