"""create tables

Revision ID: aae5fc9ed7b3
Revises: 
Create Date: 2024-11-02 16:15:53.665277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae5fc9ed7b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('context_marker', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('callback_data', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('is_half_width', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buttons'))
    )
    op.create_index(op.f('ix_buttons_context_marker'), 'buttons', ['context_marker'], unique=False)
    from fastapi_storages.integrations.sqlalchemy import FileType
    from services import main_storage
    op.create_table('media',
    sa.Column('file', FileType(main_storage), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('texts',
    sa.Column('context_marker', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('body_html', sa.String(), nullable=True),
    sa.Column('is_default_media', sa.Boolean(), nullable=False),
    sa.Column('reading_pagination', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_texts'))
    )
    op.create_index(op.f('ix_texts_context_marker'), 'texts', ['context_marker'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_new_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_users_chat_id'))
    )
    op.create_table('promocodes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_promocodes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocodes')),
    sa.UniqueConstraint('code', name=op.f('uq_promocodes_code'))
    )
    op.create_table('text_media_association',
    sa.Column('text_id', sa.UUID(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_text_media_association_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_text_media_association_text_id_texts'), ondelete='CASCADE')
    )
    op.create_table('promo_registrations',
    sa.Column('promocode_id', sa.UUID(), nullable=False),
    sa.Column('registered_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], name=op.f('fk_promo_registrations_promocode_id_promocodes')),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], name=op.f('fk_promo_registrations_registered_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_registrations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_registrations')
    op.drop_table('text_media_association')
    op.drop_table('promocodes')
    op.drop_table('users')
    op.drop_index(op.f('ix_texts_context_marker'), table_name='texts')
    op.drop_table('texts')
    op.drop_table('media')
    op.drop_index(op.f('ix_buttons_context_marker'), table_name='buttons')
    op.drop_table('buttons')
    # ### end Alembic commands ###
