"""upd text model

Revision ID: f591e3c0a74d
Revises: aae5fc9ed7b3
Create Date: 2024-11-04 04:02:21.235850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f591e3c0a74d'
down_revision: Union[str, None] = 'aae5fc9ed7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'body_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('body_html', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
