"""sent test table add

Revision ID: 656393bdef56
Revises: b741c2bf91cb
Create Date: 2024-11-21 01:51:58.790316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656393bdef56'
down_revision: Union[str, None] = 'b741c2bf91cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_tests',
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_username', sa.String(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_username', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'COMPLETED', 'REJECTED', name='teststatus'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_score', sa.String(), nullable=True),
    sa.Column('result_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_tests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_tests')
    # ### end Alembic commands ###
