"""test new fields

Revision ID: 3d880151c04d
Revises: 73735bfa034a
Create Date: 2024-11-12 22:52:55.847086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d880151c04d'
down_revision: Union[str, None] = '73735bfa034a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_results', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'category_id')
    op.drop_column('quiz_results', 'category_id')
    # ### end Alembic commands ###
