"""empty message

Revision ID: 688b5265a6a1
Revises: 3d880151c04d
Create Date: 2024-11-17 14:08:11.908453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688b5265a6a1'
down_revision: Union[str, None] = '3d880151c04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('multi_graph_results', sa.Boolean(), nullable=False))
    op.drop_column('tests', 'multy_graph_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('multy_graph_results', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tests', 'multi_graph_results')
    # ### end Alembic commands ###
