"""test key spelling fix

Revision ID: cbbad9c67fe2
Revises: bf290acf7783
Create Date: 2024-11-22 04:40:00.229733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbad9c67fe2'
down_revision: Union[str, None] = 'bf290acf7783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_psychological', sa.Boolean(), nullable=False))
    op.drop_column('tests', 'is_psycological')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_psycological', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tests', 'is_psychological')
    # ### end Alembic commands ###
