"""quiz added

Revision ID: 73735bfa034a
Revises: 6a105cba6d98
Create Date: 2024-11-11 16:40:46.500128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_storages.integrations.sqlalchemy import FileType
from services import quiz_storage


# revision identifiers, used by Alembic.
revision: str = '73735bfa034a'
down_revision: Union[str, None] = '6a105cba6d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_psycological', sa.Boolean(), nullable=False),
    sa.Column('multy_graph_results', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('picture', FileType(quiz_storage), nullable=True),
    sa.Column('allow_back', sa.Boolean(), nullable=False),
    sa.Column('allow_play_again', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_table('questions',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('picture', FileType(quiz_storage), nullable=True),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('intro_text', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('answer1_text', sa.String(), nullable=True),
    sa.Column('answer1_score', sa.Integer(), nullable=True),
    sa.Column('answer2_text', sa.String(), nullable=True),
    sa.Column('answer2_score', sa.Integer(), nullable=True),
    sa.Column('answer3_text', sa.String(), nullable=True),
    sa.Column('answer3_score', sa.Integer(), nullable=True),
    sa.Column('answer4_text', sa.String(), nullable=True),
    sa.Column('answer4_score', sa.Integer(), nullable=True),
    sa.Column('answer5_text', sa.String(), nullable=True),
    sa.Column('answer5_score', sa.Integer(), nullable=True),
    sa.Column('answer6_text', sa.String(), nullable=True),
    sa.Column('answer6_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(answer1_text IS NOT NULL AND answer1_score IS NOT NULL) OR (answer1_text IS NULL AND answer1_score IS NULL)', name=op.f('ck_questions_check_answer1_completeness')),
    sa.CheckConstraint('(answer2_text IS NOT NULL AND answer2_score IS NOT NULL) OR (answer2_text IS NULL AND answer2_score IS NULL)', name=op.f('ck_questions_check_answer2_completeness')),
    sa.CheckConstraint('(answer3_text IS NOT NULL AND answer3_score IS NOT NULL) OR (answer3_text IS NULL AND answer3_score IS NULL)', name=op.f('ck_questions_check_answer3_completeness')),
    sa.CheckConstraint('(answer4_text IS NOT NULL AND answer4_score IS NOT NULL) OR (answer4_text IS NULL AND answer4_score IS NULL)', name=op.f('ck_questions_check_answer4_completeness')),
    sa.CheckConstraint('(answer5_text IS NOT NULL AND answer5_score IS NOT NULL) OR (answer5_text IS NULL AND answer5_score IS NULL)', name=op.f('ck_questions_check_answer5_completeness')),
    sa.CheckConstraint('(answer6_text IS NOT NULL AND answer6_score IS NOT NULL) OR (answer6_text IS NULL AND answer6_score IS NULL)', name=op.f('ck_questions_check_answer6_completeness')),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_questions_test_id_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('quiz_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('is_psychological', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('result_text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_quiz_results_test_id_tests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_results_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_results'))
    )
    op.create_table('results',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('picture', FileType(quiz_storage), nullable=True),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_results_test_id_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('quiz_results')
    op.drop_table('questions')
    op.drop_table('tests')
    # ### end Alembic commands ###
