"""create promo tables

Revision ID: 2e34bc1fff0e
Revises: 0ef0a86408ff
Create Date: 2024-11-02 12:03:53.606849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e34bc1fff0e'
down_revision: Union[str, None] = '0ef0a86408ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_promocodes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocodes')),
    sa.UniqueConstraint('code', name=op.f('uq_promocodes_code'))
    )
    op.create_table('promo_registrations',
    sa.Column('promocode_id', sa.UUID(), nullable=False),
    sa.Column('registered_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], name=op.f('fk_promo_registrations_promocode_id_promocodes')),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], name=op.f('fk_promo_registrations_registered_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_registrations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_registrations')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
