"""added test pack name field to test pack completion

Revision ID: 9f0af9f3590e
Revises: fed530cd0d42
Create Date: 2025-02-01 04:15:11.241669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0af9f3590e'
down_revision: Union[str, None] = 'fed530cd0d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_pack_completions', sa.Column('test_pack_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_pack_completions', 'test_pack_name')
    # ### end Alembic commands ###
