"""Create TestPackCompletion model

Revision ID: 189ddcc09b2d
Revises: a2d84e9bf18b
Create Date: 2025-01-29 18:23:42.733788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189ddcc09b2d'
down_revision: Union[str, None] = 'a2d84e9bf18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_pack_completions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_data', sa.JSON(), nullable=False),
    sa.Column('test_pack_id', sa.Uuid(), nullable=False),
    sa.Column('test_pack_creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'ORIGIN_DELETED', 'USER_DECLINED', name='completionstatus'), nullable=False),
    sa.Column('tests_to_complete', sa.JSON(), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_pack_completions'))
    )
    op.drop_constraint('fk_test_pack_custom_tests_test_pack_id_test_packs', 'test_pack_custom_tests', type_='foreignkey')
    op.drop_constraint('fk_test_pack_custom_tests_custom_test_id_custom_tests', 'test_pack_custom_tests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_pack_custom_tests_custom_test_id_custom_tests'), 'test_pack_custom_tests', 'custom_tests', ['custom_test_id'], ['id'])
    op.create_foreign_key(op.f('fk_test_pack_custom_tests_test_pack_id_test_packs'), 'test_pack_custom_tests', 'test_packs', ['test_pack_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_pack_custom_tests_test_pack_id_test_packs'), 'test_pack_custom_tests', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_pack_custom_tests_custom_test_id_custom_tests'), 'test_pack_custom_tests', type_='foreignkey')
    op.create_foreign_key('fk_test_pack_custom_tests_custom_test_id_custom_tests', 'test_pack_custom_tests', 'custom_tests', ['custom_test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_test_pack_custom_tests_test_pack_id_test_packs', 'test_pack_custom_tests', 'test_packs', ['test_pack_id'], ['id'], ondelete='CASCADE')
    op.drop_table('test_pack_completions')
    # ### end Alembic commands ###
