"""index for creator id in completions

Revision ID: 4623a72d248e
Revises: d56abc201f17
Create Date: 2025-02-07 14:47:56.068071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4623a72d248e'
down_revision: Union[str, None] = 'd56abc201f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_test_pack_creator_id', 'test_pack_completions', ['test_pack_creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_test_pack_creator_id', table_name='test_pack_completions')
    # ### end Alembic commands ###
