"""many-to-many models on delete behav edit

Revision ID: 4fbc289a94f6
Revises: 189ddcc09b2d
Create Date: 2025-01-29 19:59:56.936302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbc289a94f6'
down_revision: Union[str, None] = '189ddcc09b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_test_pack_custom_tests_custom_test_id_custom_tests', 'test_pack_custom_tests', type_='foreignkey')
    op.drop_constraint('fk_test_pack_custom_tests_test_pack_id_test_packs', 'test_pack_custom_tests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_pack_custom_tests_custom_test_id_custom_tests'), 'test_pack_custom_tests', 'custom_tests', ['custom_test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_test_pack_custom_tests_test_pack_id_test_packs'), 'test_pack_custom_tests', 'test_packs', ['test_pack_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_test_pack_tests_test_id_tests', 'test_pack_tests', type_='foreignkey')
    op.drop_constraint('fk_test_pack_tests_test_pack_id_test_packs', 'test_pack_tests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_pack_tests_test_id_tests'), 'test_pack_tests', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_test_pack_tests_test_pack_id_test_packs'), 'test_pack_tests', 'test_packs', ['test_pack_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_pack_tests_test_pack_id_test_packs'), 'test_pack_tests', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_pack_tests_test_id_tests'), 'test_pack_tests', type_='foreignkey')
    op.create_foreign_key('fk_test_pack_tests_test_pack_id_test_packs', 'test_pack_tests', 'test_packs', ['test_pack_id'], ['id'])
    op.create_foreign_key('fk_test_pack_tests_test_id_tests', 'test_pack_tests', 'tests', ['test_id'], ['id'])
    op.drop_constraint(op.f('fk_test_pack_custom_tests_test_pack_id_test_packs'), 'test_pack_custom_tests', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_pack_custom_tests_custom_test_id_custom_tests'), 'test_pack_custom_tests', type_='foreignkey')
    op.create_foreign_key('fk_test_pack_custom_tests_test_pack_id_test_packs', 'test_pack_custom_tests', 'test_packs', ['test_pack_id'], ['id'])
    op.create_foreign_key('fk_test_pack_custom_tests_custom_test_id_custom_tests', 'test_pack_custom_tests', 'custom_tests', ['custom_test_id'], ['id'])
    # ### end Alembic commands ###
