"""add ai transcription field to test pack completion

Revision ID: d56abc201f17
Revises: 9f0af9f3590e
Create Date: 2025-02-05 06:25:24.952930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56abc201f17'
down_revision: Union[str, None] = '9f0af9f3590e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_pack_completions', sa.Column('ai_transcription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_pack_completions', 'ai_transcription')
    # ### end Alembic commands ###
