"""create tests packs table

Revision ID: 97fdc76ef75a
Revises: a9d1a297a165
Create Date: 2025-01-12 20:16:26.010730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fdc76ef75a'
down_revision: Union[str, None] = 'a9d1a297a165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_packs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('creator_username', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_packs'))
    )
    op.create_table('test_pack_tests',
    sa.Column('test_pack_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_pack_tests_test_id_tests')),
    sa.ForeignKeyConstraint(['test_pack_id'], ['test_packs.id'], name=op.f('fk_test_pack_tests_test_pack_id_test_packs')),
    sa.PrimaryKeyConstraint('test_pack_id', 'test_id', name=op.f('pk_test_pack_tests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_pack_tests')
    op.drop_table('test_packs')
    # ### end Alembic commands ###
