"""test pack completion upd

Revision ID: fed530cd0d42
Revises: 4fbc289a94f6
Create Date: 2025-01-31 23:38:51.178390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fed530cd0d42'
down_revision: Union[str, None] = '4fbc289a94f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_pack_completions', sa.Column('pending_tests', sa.ARRAY(sa.JSON()), nullable=False))
    op.add_column('test_pack_completions', sa.Column('completed_tests', sa.ARRAY(sa.JSON()), nullable=False))
    op.drop_column('test_pack_completions', 'tests_to_complete')
    op.drop_column('test_pack_completions', 'progress_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_pack_completions', sa.Column('progress_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('test_pack_completions', sa.Column('tests_to_complete', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('test_pack_completions', 'completed_tests')
    op.drop_column('test_pack_completions', 'pending_tests')
    # ### end Alembic commands ###
