"""index for creator id in custom tests and test packs

Revision ID: e42204271a0c
Revises: 4623a72d248e
Create Date: 2025-02-07 14:52:13.130461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42204271a0c'
down_revision: Union[str, None] = '4623a72d248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_custom_test_creator_id', 'custom_tests', ['creator_id'], unique=False)
    op.create_index('idx_pack_creator_id', 'test_packs', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pack_creator_id', table_name='test_packs')
    op.drop_index('idx_custom_test_creator_id', table_name='custom_tests')
    # ### end Alembic commands ###
